version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: [ "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./be:/opt/rocket-lab/challenge/be
    environment:
      MONGODB_USER: ${MONGODB_ROOT_USER}
      MONGODB_PASS: ${MONGODB_ROOT_PASSWORD}

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: rocket-lab
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - dbdata:/data/db

volumes:
  dbdata:
